### ISSUE TITLE
rolloff outputs gmon.out

### ISSUE THREAD

**Issue by jlrf98** [DReichLab/AdmixTools#1]
Hi,
I am running admixtools 3.0, downloaded June 29, 2015. I'm running this on Fedora Linux. When I run ROLLOFF, the log file looks OK after completion, but the only output file is "gmon.out". What is this file, and what is going on?
Thanks,
Juan

**Comment by mengyao** [comment]
Dear Juan,

rolloff should give you other output files. 

It is possible that you used the wrong parameter file. 

I just added some new example files here:
https://github.com/DReichLab/AdmixTools/tree/master/rolloff <https://github.com/DReichLab/AdmixTools/tree/master/rolloff>

parRolloff.panel1 <https://github.com/DReichLab/AdmixTools/blob/master/rolloff/parRolloff.panel1> is an example parameter file.

If you still have problem with running rolloff, please send me your parameter file, so that I can have a check.

Yours,

Mengyao
