### ISSUE TITLE
qpAdm source file is missing

### ISSUE THREAD

**Issue by biogberg** [DReichLab/AdmixTools#2]
Hi,

Build dies with error
make: **\* No rule to make target 'qpAdm.o', needed by 'qpAdm'.  Stop.

I appears that a source file (qpAdm.c?) is missing from the repository.

The same appears to be true for the source file for target qpWave.o.

Regards,

Bernt

**Comment by mengyao** [comment]
Dear Bernt,

I apologize that I didn’t put qpAdm.c onto gitHub due to the version change.

Now, it should be there. Please have a check.

Yours,

Mengyao

On Oct 29, 2015, at 5:36 AM, biogberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Build dies with error
make: *** No rule to make target 'qpAdm.o', needed by 'qpAdm'. Stop.

I appears that a source file (qpAdm.c?) is missing from the repository.

Regards,

Bernt

**Comment by biogberg** [comment]
Hi,

Thanks!

The build of qpAdm now dies with 

`make: *** No rule to make target 'f4rank.o', needed by 'qpAdm'.  Stop.`

Presumably the corresponding source file (f4rank.c?) is missing.

The build of qpWave is missing the source file for qpWave.o.

Regards,

Bernt
